name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Your release tag"
        required: true
  release:
    types: [published]

jobs:
  # -------------------
  # 1️⃣ 构建所有版本（只执行一次）
  # -------------------
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build all versions
        run: ./gradlew build
        env:
          BUILD_RELEASE: "true"
          CHANGELOG: ${{ github.event.inputs.tag }}

      # 上传每个版本的 jar 为单独 artifact
      - name: Upload artifacts per version
        run: |
          for v in 1.19.4 1.20.1 1.20.4 1.20.6 1.21 1.21.1 1.21.2 1.21.4 1.21.5 1.21.8; do
            echo "Uploading artifact for $v"
            npx @actions/upload-artifact@v4 \
              --name build-artifact-$v \
              --path versions/$v/build/libs/*[!sources][!shadow].jar
          done

  # -------------------
  # 2️⃣ Matrix 上传，每个 Job 使用对应版本的 artifact
  # -------------------
  upload:
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        mc_version: [1.19.4, 1.20.1, 1.20.4, 1.20.6, 1.21, 1.21.1, 1.21.2, 1.21.4, 1.21.5, 1.21.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact for this version
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-${{ matrix.mc_version }}
          path: build-artifacts

      - name: Set jar path
        id: jar
        run: echo "path=build-artifacts/*" >> $GITHUB_OUTPUT

      - name: Upload to Modrinth
        uses: Kira-NT/mc-publish@v3.3
        with:
          modrinth-id: 175yf82Z
          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}
          files: ${{ steps.jar.outputs.path }}
          name: ${{ format('MyMod {0} for MC {1}', github.event.inputs.tag, matrix.mc_version) }}
          version: ${{ format('{0}-mc{1}', github.event.inputs.tag, matrix.mc_version) }}
          version-type: release
          loaders: fabric
          game-versions: ${{ matrix.mc_version }}
          dependencies: |-
            carpet(required)
          modrinth-changelog: "Released for Minecraft ${{ matrix.mc_version }} (GitHub Actions run ${{ github.run_id }})"
          retry-attempts: 3
          retry-delay: 10000

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: ${{ steps.jar.outputs.path }}
