name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Your release tag"
        required: true
  release:
    types: [published]

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Get release tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Get release info
        id: getByTag
        uses: cardinalby/git-get-release-action@1.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.TAG }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build all versions
        run: ./gradlew build
        env:
          BUILD_RELEASE: "true"
          CHANGELOG: ${{ steps.getByTag.outputs.body }}

      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: versions/*/build/libs/*[!sources][!shadow].jar

      - name: Upload each version to Modrinth
        run: |
          shopt -s extglob
          MC_VERSIONS="1.19.4 1.20.1 1.20.4 1.20.6 1.21 1.21.1 1.21.2 1.21.4 1.21.5 1.21.8"
          for v in $MC_VERSIONS; do
            JAR_FILE=$(ls versions/$v/build/libs/!(*-sources|*-dev|*-shadow).jar | head -n 1)
            echo "Uploading MC $v: $JAR_FILE"

            # 使用 mc-publish@v3.3 上传 Modrinth
            gh workflow run -f modrinth-id=175yf82Z \
                            -f modrinth-token=${{ secrets.MODRINTH_API_TOKEN }} \
                            -f files=$JAR_FILE \
                            -f name="REMS Carpet Addition ${{ env.TAG }} for MC $v" \
                            -f version="${{ env.TAG }}-mc$v" \
                            -f version-type=release \
                            -f loaders=fabric \
                            -f game-versions=$v \
                            -f dependencies="carpet(required)" \
                            -f modrinth-changelog="${{ steps.getByTag.outputs.body }}"
          done
