name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Your release tag"
        required: true
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      jars: ${{ steps.set-output.outputs.jars }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build all versions
        run: ./gradlew build
        env:
          BUILD_RELEASE: "true"
          CHANGELOG: ${{ github.event.inputs.tag }}

      - name: Save built jars
        id: set-output
        run: |
          mkdir -p build-artifacts
          # 列出所有非 sources/dev/shadow 的 jar
          JARS=$(ls versions/*/build/libs/!(*-sources|*-dev|*-shadow).jar | tr '\n' ',' | sed 's/,$//')
          echo "jars=$JARS" >> $GITHUB_OUTPUT

  publish_github:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: ${{ needs.build.outputs.jars }}

  publish_modrinth:
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        mc_version: [1.19.4, 1.20.1, 1.20.4, 1.20.6, 1.21, 1.21.1, 1.21.2, 1.21.4, 1.21.5, 1.21.8]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload to Modrinth
        uses: Kira-NT/mc-publish@v3.3
        with:
          modrinth-id: 175yf82Z
          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}

          # 只上传对应 MC 版本的 jar
          files: ${{ needs.build.outputs.jars }}
          name: REMS Carpet Addition ${{ github.event.inputs.tag }} for MC ${{ matrix.mc_version }}
          version: ${{ github.event.inputs.tag }}-mc${{ matrix.mc_version }}
          version-type: release

          loaders: fabric
          game-versions: ${{ matrix.mc_version }}
          game-version-filter: any
          dependencies: |
            carpet(required)
          modrinth-changelog: ${{ github.event.inputs.tag }}
